### ISSUE TITLE
EME v2 FPWD tracking issue

### ISSUE THREAD

**Issue by chrisn** [w3c/encrypted-media#501]
Following [discussion at TPAC 2022](https://www.w3.org/2022/09/16-mediawg-minutes.html#t16), this issue tracks the work needed to get to First Public Working Draft for EME v2.

- [x] Add encryption scheme capability detection - [WICG draft](https://wicg.github.io/encrypted-media-encryption-scheme/)
- [x] Add HDCP policy detection - [WICG draft](https://wicg.github.io/hdcp-detection/), [open issues](https://github.com/WICG/hdcp-detection/issues), and original issue: https://github.com/w3c/encrypted-media/issues/311
- [x] Add find duplicate sessions - See https://github.com/w3c/encrypted-media/issues/467, [alternative designs](https://github.com/joeyparrish/encrypted-media-find-session/blob/draft/explainer.md#alternatives-considered), and [charter review discussion](https://github.com/w3c/charter-media-wg/issues/19),  Note: The WG has since decided not to include this in EME v2.

We also have issues labelled as [V2](https://github.com/w3c/encrypted-media/milestone/5) and [V2-Bugfixes](https://github.com/w3c/encrypted-media/milestone/6), but my understanding is that publishing FPWD isn't dependent on these (aside from https://github.com/w3c/encrypted-media/issues/467).

**Comment by chrisn** [comment]
@gregwfreedman @joeyparrish @xhwang-chromium We can schedule meeting time as needed to progress or triage issues, just let me know.

**Comment by xhwang-chromium** [comment]
Since last WG meeting in late March 2023 , we triaged existing EME issues and added labels to them.
- [V2 issues](https://github.com/w3c/encrypted-media/milestone/5) should go into the FPWD.
- [V3 issues](https://github.com/w3c/encrypted-media/milestone/7) will go into the next charter.
- [Backlog issues](https://github.com/w3c/encrypted-media/milestone/2) will needs to be triaged

Since then we have not made much progress on closing the V2 issues.

We discussed about this briefly in yesterday's (March 16, 2023) WG meeting. It'd be great if we close out the V2 issues and make the FPWD available.

**Comment by joeyparrish** [comment]
I have PRs up for most open issues in the V2 milestone, except:

 - https://github.com/w3c/encrypted-media/issues/521, where I proposed some text and am waiting for feedback before implementing
 - https://github.com/w3c/encrypted-media/issues/510, where I believe https://github.com/whatwg/html/pull/6242 would be part of the fix
 - https://github.com/w3c/encrypted-media/issues/511 and https://github.com/w3c/encrypted-media/issues/512, which would appear to be wrapped up in #510 as well

**Comment by chrisn** [comment]
Thank you! I think we can go ahead to request FPWD independently of those, so I'll raise a call for consensus.

**Comment by joeyparrish** [comment]
Sounds good

**Comment by gregwfreedman** [comment]
SGTM
